### PR TITLE
Create db model

### PR DESCRIPTION
**Pull request by Chase-Rogers**
Just for initial review. I will be adding the CRUD for the rest of the models.

I added the CRUD to server for the combo along with an endpoint. I laid out the db models as well.

### CODE REVIEW

**Comment by Chase-Rogers** [comment]
draft review done

**Review by sethpow — COMMENTED** [review]
Looks good

**Review by sethpow — COMMENTED** [review]
Looks good

**Review by a-newcomer — COMMENTED** [review]
Wow, I really appreciate all the work you've done here ! I do have some issues with the way data is modeled - I think there are several places where it would be useful to use Schema.Types.ObjectId to be able to access data. I haven't taken a close at the routers you wrote yet, either, but I'm afraid we may eventually be having to write some pretty complicated queries for it - but we can get into all that later - for now - great, thanks!

**Pull request closed without merging**
